import React from 'react';
import Head from 'next/head';
import InquiryForm from '../../components/InquiryForm';

export default function Article() {
  return (
    <div className="bg-white min-h-screen">
      <Head>
        <title>Circular Economics: Calculating the Carbon-Offset ROI for 100% Recycled B2B Packaging | Saide Packaging</title>
        <meta name="description" content="A 2026 ESG packaging procurement ROI analysis focused on carbon-offset math for 100% recycled B2B packaging sets." />
      </Head>
      
      <article className="max-w-4xl mx-auto px-4 py-16">
        <header className="mb-12">
          <h1 className="text-4xl md:text-5xl font-black mb-6 tracking-tight text-gray-900 font-montserrat">
            Circular Economics: Calculating the Carbon-Offset ROI for 100% Recycled B2B Packaging Sets in 2026
          </h1>
          <p className="text-xl text-gray-600 font-medium font-inter">
            Article 163: Turning ESG compliance into a financial asset through carbon-offset ROI modeling for sustainable packaging.
          </p>
        </header>

        <section className="prose prose-lg max-w-none text-gray-800 font-inter">
          <p>
            By 2026, <strong>sustainable packaging</strong> is no longer a "nice-to-have" ESG checkbox. It is a critical component of corporate tax optimization and brand equity. Our <strong>2026 ESG packaging procurement ROI analysis</strong> demonstrates how 100% recycled materials actually lower the total cost of ownership (TCO) when factoring in carbon credits.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4 font-montserrat">The Carbon-Offset ROI Formula</h2>
          <p>
            Modern procurement teams are moving beyond unit price to <strong>Carbon-Offset ROI (COR)</strong>. This formula accounts for the savings generated by avoiding plastic taxes and leveraging green logistics subsidies.
          </p>

          <div className="bg-gray-50 p-6 rounded-xl font-mono text-center my-8 text-gray-900 border border-gray-100">
            COR = (T_avoided + G_subsidy) / (P_sustainable - P_virgin)
          </div>
          <p className="text-sm text-center text-gray-500 italic">
            Where COR is Carbon-Offset ROI, T_avoided is plastic/carbon tax avoided, G_subsidy is green procurement subsidy, and (P_sustainable - P_virgin) is the material price premium.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4 font-montserrat">Technical Spec Table: Carbon Offset vs Material Type</h2>
          <div className="overflow-x-auto my-8 font-inter">
            <table className="w-full border-collapse border border-gray-200">
              <thead className="bg-gray-50 text-xs uppercase tracking-wider">
                <tr>
                  <th className="border border-gray-200 p-4 text-left font-black">Material Type</th>
                  <th className="border border-gray-200 p-4 text-left font-black">Carbon Offset (%)</th>
                  <th className="border border-gray-200 p-4 text-left font-black">2026 ESG Rating</th>
                </tr>
              </thead>
              <tbody className="text-sm">
                <tr>
                  <td className="border border-gray-200 p-4 font-bold text-[#C9A84C]">Virgin SBS Board</td>
                  <td className="border border-gray-200 p-4">0% (Baseline)</td>
                  <td className="border border-gray-200 p-4 text-gray-600">E-Rating (High Tax)</td>
                </tr>
                <tr>
                  <td className="border border-gray-200 p-4 font-bold text-[#C9A84C]">50% PCR Recycled</td>
                  <td className="border border-gray-200 p-4">35% Reduction</td>
                  <td className="border border-gray-200 p-4 text-gray-600">B-Rating (Tax Neutral)</td>
                </tr>
                <tr>
                  <td className="border border-gray-200 p-4 font-bold text-[#C9A84C]">100% Recycled Fiber</td>
                  <td className="border border-gray-200 p-4">68% Reduction</td>
                  <td className="border border-gray-200 p-4 text-gray-600">A+ Rating (Tax Credit)</td>
                </tr>
              </tbody>
            </table>
          </div>

          <p>
            At Saide Packaging, we help B2B brands navigate the <strong>circular economics</strong> of the 2026 market. Whether you're sourcing <strong>custom magnetic gift boxes</strong> or high-volume <strong>mailer boxes</strong>, our <strong>12H Dieline Support</strong> includes a carbon-footprint audit to ensure your procurement meets global ESG targets.
          </p>
          
          <div className="mt-12 p-8 bg-gray-900 text-white rounded-3xl border border-[#C9A84C]/20 shadow-2xl">
            <h3 className="text-2xl font-black mb-4 font-montserrat uppercase italic tracking-tighter">Optimize Your ESG ROI</h3>
            <p className="mb-6 font-inter opacity-80 text-lg">Don't wait for the 2026 plastic taxes to hit. Use our 12H Dieline Support to redesign your packaging for maximum carbon-offset ROI today.</p>
            <a href="#inquiry-form" className="inline-block bg-[#C9A84C] text-black px-10 py-4 rounded-full font-black uppercase tracking-widest hover:bg-white transition-all font-montserrat text-sm shadow-xl">
              Start Your ESG Audit
            </a>
          </div>
        </section>

        <div id="inquiry-form" className="mt-24 pt-16 border-t border-gray-100">
          <h2 className="text-3xl font-black mb-8 tracking-tighter uppercase italic font-montserrat">ESG Procurement Engineering</h2>
          <InquiryForm productTitle="Circular Economics ROI Guide" />
        </div>
      </article>
    </div>
  );
}
